# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intersite_management.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='intersite_management.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x1aintersite_management.proto\"Q\n\x0eSiteIdentifier\x12\x11\n\tsite_uuid\x18\x01 \x01(\t\x12\x11\n\tsite_name\x18\x02 \x01(\t\x12\x19\n\x11organization_name\x18\x03 \x01(\t\"I\n\nSystemType\x12\x18\n\x10system_type_uuid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\xef\x01\n\x0eSystemInstance\x12\x18\n\x10system_type_uuid\x18\x01 \x01(\t\x12\x15\n\rinstance_uuid\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x33\n\nproperties\x18\x06 \x03(\x0b\x32\x1f.SystemInstance.PropertiesEntry\x12\x13\n\x0bservice_uri\x18\x07 \x01(\t\x1a\x31\n\x0fPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xe9\x01\n\x0fSystemHeartbeat\x12 \n\x0bsystem_type\x18\x01 \x01(\x0b\x32\x0b.SystemType\x12(\n\x0fsystem_instance\x18\x02 \x01(\x0b\x32\x0f.SystemInstance\x12\x33\n\x18system_status_color_code\x18\x03 \x01(\x0e\x32\x11.StatusColorCodes\x12\x1c\n\x14short_status_message\x18\x04 \x01(\t\x12\x1f\n\x17\x64\x65tailed_status_message\x18\x05 \x01(\t\x12\x16\n\x0eunix_timestamp\x18\x06 \x01(\x02\"w\n\x18IntersiteStatusBroadcast\x12 \n\x07site_id\x18\x01 \x01(\x0b\x32\x0f.SiteIdentifier\x12,\n\x10system_heartbeat\x18\x02 \x01(\x0b\x32\x10.SystemHeartbeatH\x00\x42\x0b\n\tbroadcast*2\n\x10StatusColorCodes\x12\t\n\x05GREEN\x10\x00\x12\n\n\x06YELLOW\x10\x01\x12\x07\n\x03RED\x10\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUSCOLORCODES = _descriptor.EnumDescriptor(
  name='StatusColorCodes',
  full_name='StatusColorCodes',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GREEN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YELLOW', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RED', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=787,
  serialized_end=837,
)
_sym_db.RegisterEnumDescriptor(_STATUSCOLORCODES)

StatusColorCodes = enum_type_wrapper.EnumTypeWrapper(_STATUSCOLORCODES)
GREEN = 0
YELLOW = 1
RED = 2



_SITEIDENTIFIER = _descriptor.Descriptor(
  name='SiteIdentifier',
  full_name='SiteIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_uuid', full_name='SiteIdentifier.site_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='site_name', full_name='SiteIdentifier.site_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organization_name', full_name='SiteIdentifier.organization_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=111,
)


_SYSTEMTYPE = _descriptor.Descriptor(
  name='SystemType',
  full_name='SystemType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_type_uuid', full_name='SystemType.system_type_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='SystemType.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='SystemType.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=186,
)


_SYSTEMINSTANCE_PROPERTIESENTRY = _descriptor.Descriptor(
  name='PropertiesEntry',
  full_name='SystemInstance.PropertiesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='SystemInstance.PropertiesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SystemInstance.PropertiesEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=428,
)

_SYSTEMINSTANCE = _descriptor.Descriptor(
  name='SystemInstance',
  full_name='SystemInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_type_uuid', full_name='SystemInstance.system_type_uuid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instance_uuid', full_name='SystemInstance.instance_uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='SystemInstance.name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='SystemInstance.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='SystemInstance.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='properties', full_name='SystemInstance.properties', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='service_uri', full_name='SystemInstance.service_uri', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SYSTEMINSTANCE_PROPERTIESENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=428,
)


_SYSTEMHEARTBEAT = _descriptor.Descriptor(
  name='SystemHeartbeat',
  full_name='SystemHeartbeat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='system_type', full_name='SystemHeartbeat.system_type', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_instance', full_name='SystemHeartbeat.system_instance', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_status_color_code', full_name='SystemHeartbeat.system_status_color_code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='short_status_message', full_name='SystemHeartbeat.short_status_message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detailed_status_message', full_name='SystemHeartbeat.detailed_status_message', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unix_timestamp', full_name='SystemHeartbeat.unix_timestamp', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=431,
  serialized_end=664,
)


_INTERSITESTATUSBROADCAST = _descriptor.Descriptor(
  name='IntersiteStatusBroadcast',
  full_name='IntersiteStatusBroadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='site_id', full_name='IntersiteStatusBroadcast.site_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_heartbeat', full_name='IntersiteStatusBroadcast.system_heartbeat', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='broadcast', full_name='IntersiteStatusBroadcast.broadcast',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=666,
  serialized_end=785,
)

_SYSTEMINSTANCE_PROPERTIESENTRY.containing_type = _SYSTEMINSTANCE
_SYSTEMINSTANCE.fields_by_name['properties'].message_type = _SYSTEMINSTANCE_PROPERTIESENTRY
_SYSTEMHEARTBEAT.fields_by_name['system_type'].message_type = _SYSTEMTYPE
_SYSTEMHEARTBEAT.fields_by_name['system_instance'].message_type = _SYSTEMINSTANCE
_SYSTEMHEARTBEAT.fields_by_name['system_status_color_code'].enum_type = _STATUSCOLORCODES
_INTERSITESTATUSBROADCAST.fields_by_name['site_id'].message_type = _SITEIDENTIFIER
_INTERSITESTATUSBROADCAST.fields_by_name['system_heartbeat'].message_type = _SYSTEMHEARTBEAT
_INTERSITESTATUSBROADCAST.oneofs_by_name['broadcast'].fields.append(
  _INTERSITESTATUSBROADCAST.fields_by_name['system_heartbeat'])
_INTERSITESTATUSBROADCAST.fields_by_name['system_heartbeat'].containing_oneof = _INTERSITESTATUSBROADCAST.oneofs_by_name['broadcast']
DESCRIPTOR.message_types_by_name['SiteIdentifier'] = _SITEIDENTIFIER
DESCRIPTOR.message_types_by_name['SystemType'] = _SYSTEMTYPE
DESCRIPTOR.message_types_by_name['SystemInstance'] = _SYSTEMINSTANCE
DESCRIPTOR.message_types_by_name['SystemHeartbeat'] = _SYSTEMHEARTBEAT
DESCRIPTOR.message_types_by_name['IntersiteStatusBroadcast'] = _INTERSITESTATUSBROADCAST
DESCRIPTOR.enum_types_by_name['StatusColorCodes'] = _STATUSCOLORCODES

SiteIdentifier = _reflection.GeneratedProtocolMessageType('SiteIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _SITEIDENTIFIER,
  __module__ = 'intersite_management_pb2'
  # @@protoc_insertion_point(class_scope:SiteIdentifier)
  ))
_sym_db.RegisterMessage(SiteIdentifier)

SystemType = _reflection.GeneratedProtocolMessageType('SystemType', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMTYPE,
  __module__ = 'intersite_management_pb2'
  # @@protoc_insertion_point(class_scope:SystemType)
  ))
_sym_db.RegisterMessage(SystemType)

SystemInstance = _reflection.GeneratedProtocolMessageType('SystemInstance', (_message.Message,), dict(

  PropertiesEntry = _reflection.GeneratedProtocolMessageType('PropertiesEntry', (_message.Message,), dict(
    DESCRIPTOR = _SYSTEMINSTANCE_PROPERTIESENTRY,
    __module__ = 'intersite_management_pb2'
    # @@protoc_insertion_point(class_scope:SystemInstance.PropertiesEntry)
    ))
  ,
  DESCRIPTOR = _SYSTEMINSTANCE,
  __module__ = 'intersite_management_pb2'
  # @@protoc_insertion_point(class_scope:SystemInstance)
  ))
_sym_db.RegisterMessage(SystemInstance)
_sym_db.RegisterMessage(SystemInstance.PropertiesEntry)

SystemHeartbeat = _reflection.GeneratedProtocolMessageType('SystemHeartbeat', (_message.Message,), dict(
  DESCRIPTOR = _SYSTEMHEARTBEAT,
  __module__ = 'intersite_management_pb2'
  # @@protoc_insertion_point(class_scope:SystemHeartbeat)
  ))
_sym_db.RegisterMessage(SystemHeartbeat)

IntersiteStatusBroadcast = _reflection.GeneratedProtocolMessageType('IntersiteStatusBroadcast', (_message.Message,), dict(
  DESCRIPTOR = _INTERSITESTATUSBROADCAST,
  __module__ = 'intersite_management_pb2'
  # @@protoc_insertion_point(class_scope:IntersiteStatusBroadcast)
  ))
_sym_db.RegisterMessage(IntersiteStatusBroadcast)


_SYSTEMINSTANCE_PROPERTIESENTRY.has_options = True
_SYSTEMINSTANCE_PROPERTIESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
